"""
    AbstractMaskPattern

Supertype for definitions of mask patterns.  
"""
abstract type AbstractMaskPattern
end

"""
    BahtinovPattern <: AbstractMaskPattern

Represents a Bahtinov mask with the following parameters:

  * `pitch` controls the distance between the slots, measured relative to the length of the
    diameter.
  * `angle` controls the angle (in degrees) between the diverging slots and the parallel slots of
    the mask. Conventionally, this is 20 degrees.
  * `proportion` is the size of the slot relative to the pitch. Conventionally, the slots are half
    the width of the pitch, but this can be varied betrween 0 and 1.

The dividers between each mask segment will match the size of the space between slots (calcuated as
`(1 - proportion) * pitch`).
"""
struct BahtinovPattern <: AbstractMaskPattern
    pitch::Float64
    angle::Float64
    proportion::Float64
    function BahtinovPattern(pitch::Real, angle::Real = 20, proportion::Real = 1/2)
        0 < proportion < 1 || throw(ArgumentError("Proportion must be strictly between 0 and 1."))
        return new(abs(pitch), abs(angle), proportion)
    end
end

"""
    MultiBahtinovPattern <: AbstractMaskPattern

Represents a multi-Bahtinov mask generated by dividing the aperture into an even number of segments
and placing the parallel and diverging portions of the mask on opposing segments.
"""
struct MultiBahtinovPattern <: AbstractMaskPattern
    symmetry::Int
    bahtinov::BahtinovPattern
end

function MultiBahtinovPattern(symmetry::Integer, pitch::Real, angle::Real, proportion::Real = 1/2)
    return MultiBahtinovPattern(symmetry, BahtinovPattern(pitch, angle, proportion))
end

"""
    CareyPattern <: AbstractMaskPattern

Represents a Carey mask, which is similar to a Bahtinov mask, but generates two pairs of spikes
rather than a pair of spikes with a moving center spike.

The mask is defined by the the following parameters:

  * `pitch` controls the distance between the slots, measured relative to the length of the
    diameter.
  * `angle1` and `angle2` controls the angle (in degrees) between each set of diverging slots.
    the mask. Conventionally, one set of spikes has a 20 degree angle, and the other set has a 24
    degree angle.
  * `proportion` is the size of the slot relative to the pitch. Conventionally, the slots are half
    the width of the pitch, but this can be varied betrween 0 and 1.
"""
struct CareyPattern <: AbstractMaskPattern
    pitch::Float64
    angle1::Float64
    angle2::Float64
    proportion::Float64
    function CareyPattern(pitch::Real, angle1::Real = 20, angle2::Real = 24, proportion::Real = 1/2)
        0 < proportion < 1 || throw(ArgumentError("Proportion must be between 0 and 1."))
        return new(pitch, angle1, angle2, proportion)
    end
end

"""
    HaleHartmannPattern{S} <: AbstractMaskPattern

Represents a Hartmann mask like that use to evaluate the optics of the Hale Telescope, an example of
which can been seen [here](https://commons.wikimedia.org/wiki/File:Hartmann_Screen.jpg).

The type `S` is any type that is used to represent the shape of the holes.
"""
struct HaleHartmannPattern{S} <: AbstractMaskPattern
    symmetry::Int
    shape::S
end
